// Wandelt Supabase-Zeilen (snake_case, Tabellenstruktur) in das Datenmodell um,
// das die bestehende Dashboard-Oberfläche erwartet (camelCase, wie vorher aus
// den lokalen Fixtures). So bleibt die Render-Logik in editorial-dashboard.tsx
// unverändert, nur die Datenquelle wechselt.

/* eslint-disable @typescript-eslint/no-explicit-any */

export function mapItem(row: any) {
  const format = row.editorial_formats;
  return {
    id: row.id,
    formatId: row.format_id,
    format: format?.name ?? '',
    category: format?.category ?? '',
    logicType: format?.logic_type ?? row.logic_type,
    title: row.title,
    subtitle: row.subtitle ?? undefined,
    status: row.status,
    eventStart: row.event_start ? row.event_start.slice(0, 10) : undefined,
    eventEnd: row.event_end ? row.event_end.slice(0, 10) : undefined,
    location: row.event_location ?? undefined,
    publicationTargetDate: row.publication_target_date ?? undefined,
    eventReferenceDate: row.event_reference_date ?? undefined,
    materialReadyDate: row.material_ready_date ?? undefined,
    contentOwner: row.content_owner,
    graphicsOwner: row.graphics_owner,
    approvalOwner: row.approval_owner,
    publishOwner: row.publish_owner,
    createdAt: row.created_at ? row.created_at.slice(0, 10) : undefined,
    people: Array.from(
      new Set([row.content_owner, row.graphics_owner, row.approval_owner, row.publish_owner].filter(Boolean)),
    ),
  };
}

export function mapPost(row: any) {
  return {
    id: row.id,
    editorialItemId: row.editorial_item_id,
    postRuleId: row.post_rule_id ?? undefined,
    type: row.post_type,
    plannedDate: row.planned_date,
    regularDate: row.regular_date ?? row.planned_date,
    status: row.status,
    conditional: row.conditional,
    conditionalState: row.conditional_state,
    lateEntry: row.late_entry,
    manuallyAdjusted: row.manually_adjusted,
    priority: row.priority,
  };
}

export function mapTask(row: any) {
  return {
    id: row.id,
    editorialItemId: row.editorial_item_id,
    postId: row.post_id ?? undefined,
    title: row.title,
    owner: row.owner_name,
    dueDate: row.due_date,
    status: row.status,
    type: row.task_type,
    blocked: row.blocked,
    relativeOffsetDays: row.relative_offset_days ?? undefined,
    autoGenerated: row.auto_generated,
  };
}

export function mapMaterial(row: any) {
  return {
    id: row.id,
    editorialItemId: row.editorial_item_id,
    title: row.title,
    type: row.material_type,
    required: row.required,
    status: row.status,
    dueDate: row.due_date ?? undefined,
    source: row.source_name ?? row.source_type ?? '',
    url: row.url ?? undefined,
    fileReference: row.file_reference ?? undefined,
  };
}

export function mapQuickLink(row: any) {
  return {
    id: row.id,
    slug: row.slug,
    label: row.label,
    url: row.url ?? '',
    sortOrder: row.sort_order,
  };
}

// UI-Statuswerte -> Spaltenname/Wert für Supabase-Updates.
export const TASK_UPDATE_FIELDS: Record<string, string> = {
  title: 'title',
  owner: 'owner_name',
  dueDate: 'due_date',
  status: 'status',
};
