export function toDate(value) {
  return new Date(`${value.slice(0, 10)}T12:00:00Z`);
}

export function iso(date) {
  return date.toISOString().slice(0, 10);
}

export function addDays(value, days) {
  const date = typeof value === 'string' ? toDate(value) : new Date(value);
  date.setUTCDate(date.getUTCDate() + days);
  return iso(date);
}

export function nextBusinessDay(value) {
  const date = typeof value === 'string' ? toDate(value) : new Date(value);
  do date.setUTCDate(date.getUTCDate() + 1);
  while (date.getUTCDay() === 0 || date.getUTCDay() === 6);
  return iso(date);
}

export function mondayOfWeek(value) {
  const date = typeof value === 'string' ? toDate(value) : new Date(value);
  const day = date.getUTCDay() || 7;
  date.setUTCDate(date.getUTCDate() - day + 1);
  return iso(date);
}

export function generateSchedule({ item, postRules, taskRules, today }) {
  const anchor = item.logicType === 'publication'
    ? item.publicationTargetDate
    : item.logicType === 'event_material'
      ? item.materialReadyDate || item.eventReferenceDate
      : item.eventStart;

  const posts = postRules
    .filter((rule) => rule.formatId === item.formatId)
    .sort((a, b) => a.offsetDays - b.offsetDays)
    .map((rule) => {
      const regularDate = addDays(anchor, rule.offsetDays);
      const lateEntry = regularDate < today;
      const plannedDate = lateEntry ? nextBusinessDay(today) : regularDate;
      const conditionalState = rule.conditional ? 'pending' : 'not_required';

      return {
        id: `${item.id}-${rule.id}`,
        editorialItemId: item.id,
        postRuleId: rule.id,
        type: rule.postType,
        plannedDate,
        regularDate,
        status: rule.conditional ? 'vorgesehen' : 'in_arbeit',
        conditional: rule.conditional,
        conditionalState,
        lateEntry,
        priority: rule.priority,
      };
    });

  const tasks = posts.flatMap((post) => {
    if (post.conditional && post.conditionalState !== 'approved') {
      return [{
        id: `${post.id}-decision`,
        editorialItemId: item.id,
        postId: post.id,
        title: `Entscheiden: ${post.type} noch sinnvoll?`,
        owner: item.contentOwner,
        dueDate: addDays(post.plannedDate, -4),
        status: 'offen',
        type: 'entscheidung',
        relativeOffsetDays: -4,
        autoGenerated: true,
      }];
    }

    return taskRules
      .filter((rule) => rule.postType === post.type || rule.postType === '*')
      .map((rule) => {
        const regularDue = addDays(post.plannedDate, rule.offsetDays);
        const dueDate = post.lateEntry && regularDue < today ? today : regularDue;
        return {
          id: `${post.id}-${rule.id}`,
          editorialItemId: item.id,
          postId: post.id,
          title: rule.title,
          owner: rule.ownerRole === 'publish' ? item.publishOwner : item.contentOwner,
          dueDate,
          status: 'offen',
          type: rule.taskType,
          relativeOffsetDays: rule.offsetDays,
          autoGenerated: true,
        };
      });
  });

  return { posts, tasks };
}

export function movePost(posts, tasks, postId, plannedDate) {
  const updatedPosts = posts.map((post) => post.id === postId ? { ...post, plannedDate, manuallyAdjusted: true } : post);
  const updatedTasks = tasks.map((task) => task.postId === postId && task.relativeOffsetDays != null
    ? { ...task, dueDate: addDays(plannedDate, task.relativeOffsetDays) }
    : task);
  return { posts: updatedPosts, tasks: updatedTasks };
}

export function postingDensity(posts) {
  return posts
    .filter((post) => !['entfallen', 'published'].includes(post.status))
    .reduce((weeks, post) => {
      const week = mondayOfWeek(post.plannedDate);
      const count = (weeks[week]?.count || 0) + 1;
      weeks[week] = {
        week,
        count,
        level: count > 3 ? 'conflict' : count === 3 ? 'full' : 'ok',
      };
      return weeks;
    }, {});
}

export function blockReasons(itemId, posts, materials) {
  const requiredMissing = materials.filter((material) =>
    material.editorialItemId === itemId && material.required && material.status !== 'vorhanden');
  if (!requiredMissing.length) return [];
  const nextPost = posts
    .filter((post) => post.editorialItemId === itemId && post.status !== 'entfallen')
    .sort((a, b) => a.plannedDate.localeCompare(b.plannedDate))[0];
  if (!nextPost) return [];
  return requiredMissing.map((material) => `${material.title} fehlt für ${nextPost.type} am ${nextPost.plannedDate}`);
}

export function matchesFilters(record, filters) {
  const matchesPerson = filters.person === 'Alle' || record.owner === filters.person || record.people?.includes(filters.person);
  const matchesStatus = filters.status === 'Alle' || record.status === filters.status;
  const matchesFormat = filters.format === 'Alle' || record.format === filters.format || record.formatName === filters.format;
  const matchesTime = filters.time === 'Alle' || record.timeBucket === filters.time;
  return matchesPerson && matchesStatus && matchesFormat && matchesTime;
}

export function reassignTask(tasks, taskId, owner) {
  if (!['Tom', 'Norbert'].includes(owner)) throw new Error('Unbekannte verantwortliche Person');
  if (!tasks.some((task) => task.id === taskId)) throw new Error('Unbekannte Aufgabe');
  return tasks.map((task) => task.id === taskId ? { ...task, owner } : task);
}
